:PROPERTIES:
:ID:       20260131T230525
:END:
#+title: 认识论

* 书籍

** Mindstorms: Children, Computers, and Powerful Ideas

Saymer Papert 面向大众的 [[https://worrydream.com/refs/Papert_1980_-_Mindstorms,_1st_ed.pdf][小书]]。国内有个还不错的 [[https://aied.pku.edu.cn/docs//2023-10/ddaa91d3e539413882964e3450799232.pdf][综述]]。作者从 1960 年的学校教育现
状和大众对计算机的观点出发，另辟蹊径地提出自己的想法：通过重新整理对知识的解释，
建立与人的心智模型更加相似、更能直接使用和体会的知识体系，计算机可以促进儿童和成
人学习原本普遍认为非常难的数学、物理等学科知识。作者的以下几个观点相互强化并贯穿
始终（我理解有限）：

- （从 Piaget 继承发展而来）学习是一种自发的过程，如果语言不需要刻意去教学，那么
  其它学科的知识理应也不需要刻意教学，哪怕它们差别很远；
- 一种“可生长”的知识结构：存在一种知识结构，与人内在的心智结构相呼应的，顺应这种
  结构来呈现知识和教学内容，相比传统（哪怕更严谨）体系，能让人更自然、高效地学习。
  比如用身体作为延伸，用海龟几何（前进后退转向）学习形式几何和微积分；
- 一种顺应这种结构的方法是，找到新知识和现有知识相近的地方，并不断强化它们的联系。
  由此提出“建造主义”：通过实践构造可触碰、具象化的东西，学习“有用”、能体会的知识；
- 学习、构建的驱动力可能是情绪的，需要找到能让人感到快乐的方式才能促进，比如“做
  到原本做不到的事情”、“幽默”、“发现美”。有些知识如数学，受限于社会文化和技术发
  展，没法从生活中直接找到这种驱动力。那就构造“小小世界”，在那里把知识和奖励关联
  起来（比如几何和好看的图像，程序和诗句）；
- 计算机非常适合用于构造“小小世界”。对计算机利用得当，可以规避它对社会文化的负面
  影响，而强化它对于学习和认识人类本身的正面影响；
- 改进社会文化来促进学习：如果教育者和被教育者实际都是学习者和探索者的身份，教学
  内容就不会脱离人的本性而难以接受和理解。如果现实世界提供足够强的驱动力，就不用
  构造“小小世界”。

他还有一些更具体的想法：

- 对于过程的描述能力是一种数学能力。如果人有更好的描述过程的能力，那就可能能通过
  描述自己的思考过程来对其反思，从而可能更好地思考；
- 物理不是为了证明某个描述世界的模型是对的，而是为了让人能更好地理解世界、构建更
  准确的直觉。

书的中间和结尾有很多引用和译注，提到了更多人的工作，值得挖掘。
