* APL 与打字机

（补档，不记得什么时候了）

之前 Youtube 推荐了 J 语言相关的视频，我又对 APL 和 Kenneth Iverson 的 [[https://www.eecg.utoronto.ca/~jzhu/csc326/readings/iverson.pdf][Notation
as a tool of thought]] 早有耳闻，于是开始试图学习起来 APL，最终找到了 [[https://www.dyalog.com/][Dyalog APL]]，
发现真的挺有趣，能看到有些想法在后面的语言里得到了应用（例如 Julia 的 broadcast）。

我甚至还找到了一些看起来更加玄妙的语言，比如 http://www.cosy.com/language/ ，作
者在一个 Forth 版本里加了 APL 相关的词汇，说自己所有的工作都在这个环境中进行。听
上去非常Forth。

不过这里想记录的是在阅读 https://www.jsoftware.com/papers/APLDesign.htm 时，读到
作者说 APL 里类似 Phi 的符号（含义应该是左右翻转），实际是在打字机上打一个圈，然
后按退格，再打一个竖线。再一次感叹，打字机对英文世界的影响真大。同时我也觉得，现
在习惯于电子屏幕的人们可能很难想象到类似的创造思路，可能只会不断寻找已经定义好的
字符，而不知道如何创造字符（以及为什么要创造）。计算机虽然给了人们创造和使用的便
利，但是一部分人比其他人更善于享受创造的便利，大部分人更多只收益于使用的便利。不
过，表情包的创造倒是非常普遍，所以这里的我想法可能过于悲观了。

* 输入法配置治愈我的计算机恐惧症

（补档，不记得什么时候了）

之前最后一次重装电脑（应该是把桌面环境换成 KDE 的时候）后，我的输入法就在 Emacs
里用不了了，后来尝试学习使用 [[https://book.gtoolkit.com/][Glamorous toolkit]] 的时候，发现也不能打中文，我当时
还以为怪这两个程序没有中文支持。我已经近三年对使用电脑产生恐惧，拒绝使用一切需要
配置和学习才能使用的软件，转而用纸笔，只用电脑阅读文档。这件事情加深了我的恐惧。

最近试图学习 [[https://factorcode.org/][Factor]] 语言，发现在它的 Listener 里也打不了中文。我开始怀疑是自己的
配置不对，而且很生气：我难道要因此再次错过新鲜事物吗？终于有一天鼓起勇气去搜了下，
不知道怎么就找到了解决方法，就是缺少了 GTK 和 xim 的配置变量。

终于能输入中文，我感到松了一口气。紧接着我发现自己曾经知道如何配置：
https://github.com/wenxin-wang/wiki/blob/master/Fcitx.org 。
再一次意识到，如果不以一种非常易于复现的方式积累经验，就是在浪费自己的时间， 过
去和未来的。

* Brother 扫描仪，4 年前给自己的馈赠

工作后没多久，我想买台扫描仪，因为觉得在纸上写字真的比打字方便，可以自由排版、画
图。万一以后能在纸上写代码，扫描到电脑里呢？会不会更方便呢？但是我的字很差，也没
有现成的纸上写代码方案。纯纸写代码交互性太差了，或许以后可以设计个方案把纸变成
REPL 的一部分。

抱着这样的畅想，我开始调研适用于 Linux 的扫描仪，结论是似乎只有 Brother 的扫描仪
比较好用，于是京东下单了一个。结果到了之后，我就对之前的想法没那么感兴趣了，也害
怕配置扫描仪会花很多时间，而且也没有太多需要扫描的东西。这个扫描仪就完全没拆封，
保留着快递包装，随着我不断搬家，换到一个个角落里。

直到最近，看着家里颇有纪念意义的草稿纸，加上新近找回一点点的对折腾电脑的勇气，我
行动起来，竟然幸运地真的配好了扫描仪，用 KDE 默认的文档扫描软件，折腾了 1 个小时
不到，就扫描出来了文档。一开始对 dpi 没有实感，调太小了，发现很糊，还以为打印机
不行；后来调到最大 600dpi，真清楚，但是文档有数十数百 MB；最终发现 150dpi 就足够
清晰，文档也不大。

我还拉着我爸分享了下折腾出来的喜悦，他似乎也听说过这个牌子。后来家里人有需求，我
也用它扫描了身份证和签名文档。这次折腾让我真的很开心。

* Spacemacs master 不支持 Emacs 29.4

眼馋老板的开发环境很久，终于鼓起勇气试图安装 Emacs。我对自己曾经的 Emacs 配置感
到非常厌倦，所以暂时就想先用现成的配置学习新鲜事物，慢慢再重拾自己的 Emacs 配置。
最终在 Doom 和 Spacemacs 两款 Emacs 发行版中选择了功能更丰富的后者。

在自己电脑上用得好好的，结果单位两台电脑上都出现了 ~defmethod~ 未定义的问题。
本来还以为是因为有残留的 ~.elc~ 文件导致，然而并没有。和自己电脑比对了下，发现
spacemacs 默认分支竟然是 develop，切换到 master 就有同样问题。

在所有的电脑上切换到了 spacemacs develop 分支，就好了。
