:PROPERTIES:
:ID:       20260131T115149
:END:
#+title: 2026-Readings

* [[https://thecreativeindependent.com/people/multi-disciplinary-artist-jack-rusher-on-the-need-to-sustain-your-creative-drive-in-the-face-of-technological-change/][On the need to sustain your creative drive in the face of technological change]]
:LOGBOOK:
CLOCK: [2026-02-01 日 20:31]--[2026-02-01 日 20:31] =>  0:00
:END:

受访者是 clerk (clojure notebook）的作者。

- 利用现存的艺术作为参考
  - 看到自然存在的物体，试图把握它的模式，在计算机上复现
  - 应用、组合不同时期的艺术风格和想法（比如无限复制一个古典风格的东西）
- 文 vs 理，运动 vs 数学 的严格区分是社会文化的产物。需要花时间尝试不擅长的东西，
  更全面地体会和发展自己
- 放弃创造是放弃与生俱来的权利
- 玩音乐、学习艺术提升了他对世界的感知，比如对节律、光源的感受。如果只用 LLM 去
  描述和生成，就失去了提升感知的机会
  - LLM 是非常好用的工具，辅助创作
- 接受不完美的作品，持续创作，也持续展示（我觉得还是得取舍，或者把私人展示也算上）
  - “Don’t hold your breath for five or seven years and not release anything,
    and then you’ve just got clogged up with way too much stuff… You lose
    contact to the part of you, your subconscious, that’s writing songs all the
    time, and the part of you that’s showing it to the world… That’s more
    important, to sustain that flow, than to wait until things are perfect.” --
    Björk, the musician
  - Excellence is just a function of habit. -- Aristotle
- 20 世纪的突破持续影响现在。当时的投资价值更加宽容，也因此更容易产出在长远阶段
  才能产生影响的技术。比如电容屏发明 25 年后用于 iPhone。前人种树，后人收获。现
  在收获多，至少明面上种树少
- 运用多种方式（条理性的推理或者整体的直觉）去理解和处理事物

作者的很多观点和 Saymer Papert 相似，尤其是在人的提升的方法和内容上。

我觉得不是每个人都能像作者那样，无需区分工作和兴趣还能过上不错的生活。但是确实可
以挤出更多的时间去体验和创作。

也需要留意，最近 5-15 年的好想法有什么？多注意种树的人，日后能用到他们的成果，也
可以参与其中。

* https://way-cooler.org/blog/2020/01/09/way-cooler-post-mortem.html
:LOGBOOK:
CLOCK: [2026-02-03 二 12:27]--[2026-02-03 二 12:40] =>  0:13
:END:

详细而真诚地讲了作者在 Wayland 尚不成熟的时候，做当时很受欢迎的 Rust+Lua 的
Compositor 四年的心路历程，从入门到退出。

技术上：前期踩了很多底层库的坑，一方面觉得自己没有调研清楚，另一方面能看出来当时
人们对 Rust 不够熟悉，Rust 可能也没有现在好用（？我还没用过）。比如作者就不知道
什么时候用/不用 unsafe Rust：看起来他后面选择了尽量用 safe Rust，但是决定推动用
C 写 wlroots，至今也不后悔；然后花了很多时间给 wlroots 写 Rust 接口，也放弃了，
因为太难保证一定 safe 了，导致他压力很大。他在工作中用 Rust，所以也不是反对 Rust，
我相信他和 Rust 在这个过程中都成熟了很多。 *合适的工具很重要* ，但是看上去 *减少
需求似乎更重要* 。

心态上： *太想获得认可* ，会让他做出日后后悔的技术选择。比如一开始选择 Rust 是因
为它火；后面为了迎合大众需求，想把 Awesome 移植到 Wayland，结果架构上完全没法平
移，而且他本人不喜欢 Awesome， *不给自己用的东西是没有爱能坚持下去的* ，最终果然
也放弃了。他觉得不应该把开源项目当产品做，而是为自己做。否则自己很累，还把朋友推
走了。
